### ISSUE TITLE
Error with Python 3.6

### ISSUE THREAD

**Issue by r0f1** [mkorpela/overrides#11]
Hi,
I just ran this program:

    from overrides import overrides

    class SuperClass(object):
        def method(self): return 2

    class SubClass(SuperClass):
        @overrides
        def method(self): return 1

And got an error message.

    Traceback (most recent call last):
      File "C:\Users\admin\Test.py", line 9, in <module>
        class SubClass(SuperClass):
      File "C:\Users\admin\Test.py", line 11, in SubClass
        @overrides
      File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\overrides\overrides.py", line 58, in overrides
        for super_class in _get_base_classes(sys._getframe(2), method.__globals__):
      File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\overrides\overrides.py", line 75, in _get_base_classes
        class_name_components in _get_base_class_names(frame)]
      File "C:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\overrides\overrides.py", line 96, in _get_base_class_names
        if type(co.co_consts[oparg]) == str:
    IndexError: tuple index out of range

It seems to me, as if this was caused by updating from Python 3.5 to 3.6.

Best,
r0f1

**Comment by villasv** [comment]
Same here, with Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32.

**Comment by AlinGlow** [comment]
Little debbuging shows, that seems to be the binary format of `<code object>.code` was changed in Py3.6.
The problem in line 84
`oparg = itemint(code[i]) + itemint(code[i+1])*256 + extended_arg`
On my windows at first step of loop with i = 1
- on Py35 `code[i+1] -> 0`
- on Py36 `code[i+1] -> 100` on same source code.
Which is cause miss on `co.co_consts[oparg]`, cuz it have same content and size on both Py35 и Py36.

Py35 format of `<code object>.code`
```
[100, 0, 0, 100, 1, 0, 108, 0, 0, 109, 0, 0, 90, 0, 0, 1, 71, 100, 2, 0, 100, 3, 0, 132, 0, 0, 100, 3, 0, 101, 1, 0, 131, 3, 0, 90, 2, 0, 71, 100, 4, 0, 100, 5, 0, 132, 0, 0, 100, 5, 0, 101, 2, 0, 131, 3, 0, 90, 3, 0, 100, 6, 0, 83]
b'd\x00\x00d\x01\x00l\x00\x00m\x00\x00Z\x00\x00\x01Gd\x02\x00d\x03\x00\x84\x00\x00d\x03\x00e\x01\x00\x83\x03\x00Z\x02\x00Gd\x04\x00d\x05\x00\x84\x00\x00d\x05\x00e\x02\x00\x83\x03\x00Z\x03\x00d\x06\x00S'
```
Py36 format of `<code object>.code`
```
[100, 0, 100, 1, 108, 0, 109, 0, 90, 0, 1, 0, 71, 0, 100, 2, 100, 3, 132, 0, 100, 3, 101, 1, 131, 3, 90, 2, 71, 0, 100, 4, 100, 5, 132, 0, 100, 5, 101, 2, 131, 3, 90, 3, 100, 6, 83, 0]
b'd\x00d\x01l\x00m\x00Z\x00\x01\x00G\x00d\x02d\x03\x84\x00d\x03e\x01\x83\x03Z\x02G\x00d\x04d\x05\x84\x00d\x05e\x02\x83\x03Z\x03d\x06S\x00'
```
Tested on Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32

**Comment by rd999** [comment]
Is there a version available for download which can cope with both Python 3.5 and 3.6?

**Comment by rd999** [comment]
I'm using this code at the moment:
`            ### PATCH BEGIN ...
            if sys.version_info < (3, 6):
               oparg = itemint(code[i]) + itemint(code[i+1])*256 + extended_arg
               extended_arg = 0
               i += 2
            else: # sys.version_info >= (3, 6)
               oparg = itemint(code[i]) + extended_arg
               extended_arg = 0
               i += 1
            ### ... PATCH END
`

**Comment by mkorpela** [comment]
@rd999 : no there is not. I have not worked for this little project for a while. Would you like to make a pull request of your little patch? I would loved to release a new version with it included and credited to all you guys.

**Comment by mkorpela** [comment]
New version 1.8 that works with 3.6 is now available from Pypi.
