### ISSUE TITLE
`overrides` is incompatible with `nuitka`

### ISSUE THREAD

**Issue by bersbersbers** [mkorpela/overrides#111]
```python
"""bug.py"""
from overrides import override

class A:
    def hello(self) -> None:
        print("A")

class B(A):
    @override
    def hello(self) -> None:
        print("B")

b = B()
b.hello()
```

```shell
$ pip install nuitka overrides
$ python bug.py
B
$ python -m nuitka bug.py
...
Nuitka:INFO: Successfully created 'bug.bin'.
$ ./bug.bin
Traceback (most recent call last):
  File "/mnt/c/code/bug.py", line 8, in <module>
    class B(A):
  File "/mnt/c/code/bug.py", line 9, in B
    @override
  File "/home/bers/.local/lib/python3.10/site-packages/overrides/overrides.py", line 143, in override
    return _overrides(method, check_signature, check_at_runtime)
  File "/home/bers/.local/lib/python3.10/site-packages/overrides/overrides.py", line 172, in _overrides
    raise TypeError(f"{method.__qualname__}: No super class method found")
TypeError: B.hello: No super class method found
```

**Comment by bersbersbers** [comment]
To me, a potential fix doesn't look too difficult:

Replace 

https://github.com/mkorpela/overrides/blob/8ad1fadf6cb64f2cba2f957e49cf46280dc838a4/overrides/overrides.py#L159

by something along these lines:

```python
    super_classes = _get_base_classes(sys._getframe(3), global_vars)
    if not super_classes:  # fix for Nuitka
        return method
    for super_class in super_classes:
```
