### ISSUE TITLE
Pip fails to install overrides

### ISSUE THREAD

**Issue by lisyarus** [mkorpela/overrides#4]
Python 3.4.0, pip 7.0.1

Command `pip install overrides` fails with

    Collecting overrides
      Using cached overrides-0.4.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-evd5k9b1/overrides/setup.py", line 5, in <module>
            from overrides import __VERSION__
          File "/tmp/pip-build-evd5k9b1/overrides/overrides/__init__.py", line 2, in <module>
            from overrides import __VERSION__
        ImportError: cannot import name '__VERSION__'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-evd5k9b1/overrides

**Comment by mkorpela** [comment]
Fixed in v 0.5
